{
  "name": "CI",
  "on": {
    "push": {
      "branches": [
        "develop"
      ]
    },
    "pull_request": null
  },
  "jobs": {
    "gate": {
      "runs-on": "ubuntu-latest",
      "env": {
        "OS": "ubuntu-latest",
        "QUICKLISP_DIST": "quicklisp",
        "LISP": "sbcl-bin"
      },
      "steps": [
        {
          "name": "Checkout Code",
          "uses": "actions/checkout@v4"
        },
        {
          "name": "Setup Common Lisp Environment",
          "uses": "40ants/setup-lisp@v4",
          "with": {
            "asdf-system": "bknr.hashkv",
            "cache": "false"
          }
        },
        {
          "name": "Gate G1-G3",
          "run": ".github/scripts/gate.ros",
          "shell": "bash"
        }
      ]
    },
    "tests": {
      "runs-on": "ubuntu-latest",
      "env": {
        "OS": "ubuntu-latest",
        "QUICKLISP_DIST": "quicklisp",
        "LISP": "sbcl-bin"
      },
      "steps": [
        {
          "name": "Checkout Code",
          "uses": "actions/checkout@v4"
        },
        {
          "name": "Setup Common Lisp Environment",
          "uses": "40ants/setup-lisp@v4",
          "with": {
            "asdf-system": "bknr.hashkv",
            "cache": "false"
          }
        },
        {
          "name": "BDD",
          "run": "./bknr.hashkv.ros bdd",
          "shell": "bash"
        },
        {
          "name": "Unit",
          "run": "./bknr.hashkv.ros test",
          "shell": "bash"
        },
        {
          "name": "End to end",
          "run": "./bknr.hashkv.ros e2e",
          "shell": "bash"
        }
      ]
    },
    "coverage": {
      "runs-on": "ubuntu-latest",
      "env": {
        "OS": "ubuntu-latest",
        "QUICKLISP_DIST": "quicklisp",
        "LISP": "sbcl-bin"
      },
      "steps": [
        {
          "name": "Checkout Code",
          "uses": "actions/checkout@v4"
        },
        {
          "name": "Setup Common Lisp Environment",
          "uses": "40ants/setup-lisp@v4",
          "with": {
            "asdf-system": "bknr.hashkv",
            "cache": "false"
          }
        },
        {
          "name": "Branch coverage, 100% required",
          "run": ".github/scripts/cover.ros",
          "shell": "bash"
        }
      ]
    },
    "docs": {
      "runs-on": "ubuntu-latest",
      "env": {
        "OS": "ubuntu-latest",
        "QUICKLISP_DIST": "quicklisp",
        "LISP": "sbcl-bin"
      },
      "steps": [
        {
          "name": "Checkout Code",
          "uses": "actions/checkout@v4"
        },
        {
          "name": "Setup Common Lisp Environment",
          "uses": "40ants/setup-lisp@v4",
          "with": {
            "asdf-system": "bknr.hashkv",
            "cache": "false"
          }
        },
        {
          "name": "Render manual",
          "run": "./bknr.hashkv.ros docs",
          "shell": "bash"
        }
      ]
    }
  }
}